/**
 * GET /api/images/:imageId
 *
 * Returns the full ImageResult for a single image: every prediction box,
 * every ground truth box, IoU values, error types, and cross-reference IDs.
 *
 * This is the heavyweight endpoint — it includes predictions and groundTruths
 * arrays that are stripped from the list endpoint. It should only be called
 * when the user opens a specific image's detail view.
 *
 * The imageId is the UUID generated by the mock data script and stored in
 * the fixture. It is stable across requests (fixtures are static).
 */
 
import { NextRequest, NextResponse } from "next/server";
import { getImageDetail } from "@/lib/store";
import type { ImageDetailResponse } from "@/types/validation";
 
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ imageId: string }> }
) {
  const { imageId } = await params;
 
  const image = getImageDetail(imageId);
  if (!image) {
    return NextResponse.json({ error: "Image not found" }, { status: 404 });
  }
 
  const body: ImageDetailResponse = { image };
  return NextResponse.json(body);
}
