/**
 * This file was auto-generated by openapi-typescript.
 * DO NOT EDIT.
 */

export interface paths {
    "/api/runs/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a full validation run summary */
        get: operations["getRunSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List image results for a run with filtering and pagination */
        get: operations["listImages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the full detail of a single image result */
        get: operations["getImageDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get error pattern groups for a run */
        get: operations["getPatterns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The five failure modes a YOLO model can produce, from most to least severe:
         *       false_positive  – Predicted box with no matching GT (hallucinated object)
         *       false_negative  – GT with no matching prediction (missed object)
         *       localization    – Right class, IoU < 0.5 (detected but poorly framed)
         *       classification  – Right location, wrong class (confused label)
         *       duplicate       – Redundant prediction suppressed by NMS
         * @enum {string}
         */
        ErrorType: "false_positive" | "false_negative" | "localization" | "classification" | "duplicate";
        /** @enum {string} */
        RunStatus: "complete" | "running" | "failed";
        /** @enum {string} */
        DataSplit: "val" | "test";
        /** @enum {string} */
        PatternGroupBy: "class" | "errorType" | "confidence";
        /** @enum {string} */
        SortOrder: "worst" | "best" | "most_errors";
        /** @description Normalised bounding box in YOLO [cx, cy, w, h] format. */
        BBox: {
            /** @description Centre-x, normalised */
            x: number;
            /** @description Centre-y, normalised */
            y: number;
            /** @description Width, normalised */
            w: number;
            /** @description Height, normalised */
            h: number;
        };
        Detection: {
            id: string;
            classId: number;
            className: string;
            confidence: number;
            bbox: components["schemas"]["BBox"];
            /** @description true if IoU >= 0.5 with a GT of the same class */
            matched: boolean;
            /** @description IoU with the best-matching GT; 0 if no match */
            iou: number;
            /** @description null for true positives */
            errorType: components["schemas"]["ErrorType"] | null;
            /** @description Link back to the GT this prediction corresponds to */
            groundTruthId: string | null;
        };
        GroundTruth: {
            id: string;
            classId: number;
            className: string;
            bbox: components["schemas"]["BBox"];
            /** @description true if a TP prediction claimed this GT */
            matched: boolean;
            matchedPredictionId: string | null;
            /** @description Closest prediction even when unmatched */
            nearestPredictionId: string | null;
            /** @description IoU with the nearest prediction; null if no predictions exist */
            nearestPredictionIou: number | null;
            /** @description null for matched GTs; the failure mode for unmatched ones */
            errorType: ("false_negative" | "localization" | "classification") | null;
        };
        /** @description Lightweight image summary for list/gallery views. Strips predictions and groundTruths to keep payloads small. */
        ImageListItem: {
            id: string;
            runId: string;
            filename: string;
            /** Format: uri */
            imageUrl: string;
            /** @description Width in pixels */
            width: number;
            /** @description Height in pixels */
            height: number;
            /** @description F1 score: 2TP / (2TP + FP + FN) */
            score: number;
            truePositives: number;
            falsePositives: number;
            falseNegatives: number;
            /** @description Highest-count error type on this image */
            dominantErrorType: components["schemas"]["ErrorType"] | null;
            /** @description Class names of GT objects present in this image */
            classesPresent: string[];
            /** @description e.g. "small_objects", "crowded" */
            tags: string[];
        };
        /** @description Full per-image validation result including all predictions and GTs. */
        ImageResult: components["schemas"]["ImageListItem"] & {
            predictions: components["schemas"]["Detection"][];
            groundTruths: components["schemas"]["GroundTruth"][];
        };
        AggregateMetrics: {
            /** @description Mean Average Precision at IoU=0.50 */
            map50: number;
            /** @description Mean Average Precision averaged over IoU=0.50:0.05:0.95 */
            map50_95: number;
            precision: number;
            recall: number;
            f1: number;
        };
        ClassMetrics: {
            classId: number;
            className: string;
            /** @description Average Precision at IoU=0.50 */
            map50: number;
            /** @description Average Precision averaged over IoU=0.50:0.05:0.95 */
            map50_95: number;
            precision: number;
            recall: number;
            f1: number;
            /** @description GT instance count for this class in the dataset */
            support: number;
            truePositives: number;
            falsePositives: number;
            falseNegatives: number;
        };
        ValidationRun: {
            id: string;
            modelId: string;
            modelName: string;
            datasetName: string;
            split: components["schemas"]["DataSplit"];
            /**
             * Format: date-time
             * @description ISO 8601 timestamp
             */
            createdAt: string;
            status: components["schemas"]["RunStatus"];
            imageCount: number;
            /** @description Ordered list of class names; index == classId */
            classNames: string[];
            aggregateMetrics: components["schemas"]["AggregateMetrics"];
            perClassMetrics: components["schemas"]["ClassMetrics"][];
            /** @description confusionMatrix[trueClassId][predictedClassId] = count */
            confusionMatrix: number[][];
        };
        /** @description Filter and sort parameters for the image list endpoint. */
        ImageFilters: {
            class?: string;
            errorType?: components["schemas"]["ErrorType"];
            confMin?: number;
            confMax?: number;
            sort: components["schemas"]["SortOrder"];
            page: number;
            pageSize: number;
        };
        PatternGroup: {
            /** @description e.g. "bird", "false_positive", "low (0–0.4)" */
            label: string;
            /** @description Number of images in this group */
            count: number;
            /** @description Mean score across the group */
            avgScore: number;
            /** @description Count of each ErrorType present in this group */
            errorBreakdown: {
                [key: string]: number;
            };
            /** @description Top 3 worst images in the group */
            representativeImageIds: string[];
            /** @description Partial ImageFilters for deep-linking back to the gallery */
            galleryParams?: {
                class?: string;
                errorType?: components["schemas"]["ErrorType"];
                confMin?: number;
                confMax?: number;
                sort?: components["schemas"]["SortOrder"];
                page?: number;
                pageSize?: number;
            };
        };
        PatternsResponse: {
            groupBy: components["schemas"]["PatternGroupBy"];
            /** @description Sorted by count descending */
            groups: components["schemas"]["PatternGroup"][];
        };
        RunSummaryResponse: {
            run: components["schemas"]["ValidationRun"];
        };
        ImageListResponse: {
            items: components["schemas"]["ImageListItem"][];
            total: number;
            page: number;
            pageSize: number;
        };
        ImageDetailResponse: {
            image: components["schemas"]["ImageResult"];
        };
    };
    responses: never;
    parameters: {
        /** @description Validation run ID */
        RunId: string;
        /** @description Image result ID */
        ImageId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRunSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Validation run ID */
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryResponse"];
                };
            };
        };
    };
    listImages: {
        parameters: {
            query?: {
                /** @description Filter by class name */
                class?: string;
                /** @description Filter by error type */
                errorType?: components["schemas"]["ErrorType"];
                /** @description Minimum confidence threshold */
                confMin?: number;
                /** @description Maximum confidence threshold */
                confMax?: number;
                sort?: components["schemas"]["SortOrder"];
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                /** @description Validation run ID */
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageListResponse"];
                };
            };
        };
    };
    getImageDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Image result ID */
                id: components["parameters"]["ImageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDetailResponse"];
                };
            };
        };
    };
    getPatterns: {
        parameters: {
            query: {
                groupBy: components["schemas"]["PatternGroupBy"];
            };
            header?: never;
            path: {
                /** @description Validation run ID */
                id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatternsResponse"];
                };
            };
        };
    };
}
