# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-05T11:01:17+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class ErrorType(Enum):
    false_positive = 'false_positive'
    false_negative = 'false_negative'
    localization = 'localization'
    classification = 'classification'
    duplicate = 'duplicate'


class RunStatus(Enum):
    complete = 'complete'
    running = 'running'
    failed = 'failed'


class DataSplit(Enum):
    val = 'val'
    test = 'test'


class PatternGroupBy(Enum):
    class_ = 'class'
    errorType = 'errorType'
    confidence = 'confidence'


class SortOrder(Enum):
    worst = 'worst'
    best = 'best'
    most_errors = 'most_errors'


class BBox(BaseModel):
    x: Annotated[float, Field(description='Centre-x, normalised', ge=0.0, le=1.0)]
    y: Annotated[float, Field(description='Centre-y, normalised', ge=0.0, le=1.0)]
    w: Annotated[float, Field(description='Width, normalised', ge=0.0, le=1.0)]
    h: Annotated[float, Field(description='Height, normalised', ge=0.0, le=1.0)]


class Detection(BaseModel):
    id: str
    classId: int
    className: str
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]
    bbox: BBox
    matched: Annotated[
        bool, Field(description='true if IoU >= 0.5 with a GT of the same class')
    ]
    iou: Annotated[
        float,
        Field(
            description='IoU with the best-matching GT; 0 if no match', ge=0.0, le=1.0
        ),
    ]
    errorType: Annotated[ErrorType | None, Field(description='null for true positives')]
    groundTruthId: Annotated[
        str | None,
        Field(description='Link back to the GT this prediction corresponds to'),
    ]


class NearestPredictionIou(RootModel[float]):
    root: Annotated[
        float,
        Field(
            description='IoU with the nearest prediction; null if no predictions exist',
            ge=0.0,
            le=1.0,
        ),
    ]


class ErrorType1(Enum):
    false_negative = 'false_negative'
    localization = 'localization'
    classification = 'classification'


class GroundTruth(BaseModel):
    id: str
    classId: int
    className: str
    bbox: BBox
    matched: Annotated[
        bool, Field(description='true if a TP prediction claimed this GT')
    ]
    matchedPredictionId: str | None
    nearestPredictionId: Annotated[
        str | None, Field(description='Closest prediction even when unmatched')
    ]
    nearestPredictionIou: Annotated[
        NearestPredictionIou | None,
        Field(
            description='IoU with the nearest prediction; null if no predictions exist'
        ),
    ]
    errorType: Annotated[
        ErrorType1 | None,
        Field(description='null for matched GTs; the failure mode for unmatched ones'),
    ]


class ImageListItem(BaseModel):
    id: str
    runId: str
    filename: str
    imageUrl: AnyUrl
    width: Annotated[int, Field(description='Width in pixels')]
    height: Annotated[int, Field(description='Height in pixels')]
    score: Annotated[
        float, Field(description='F1 score: 2TP / (2TP + FP + FN)', ge=0.0, le=1.0)
    ]
    truePositives: int
    falsePositives: int
    falseNegatives: int
    dominantErrorType: Annotated[
        ErrorType | None, Field(description='Highest-count error type on this image')
    ]
    classesPresent: Annotated[
        list[str], Field(description='Class names of GT objects present in this image')
    ]
    tags: Annotated[list[str], Field(description='e.g. "small_objects", "crowded"')]


class ImageResult(ImageListItem):
    predictions: list[Detection]
    groundTruths: list[GroundTruth]


class AggregateMetrics(BaseModel):
    map50: Annotated[float, Field(description='Mean Average Precision at IoU=0.50')]
    map50_95: Annotated[
        float,
        Field(description='Mean Average Precision averaged over IoU=0.50:0.05:0.95'),
    ]
    precision: float
    recall: float
    f1: float


class ClassMetrics(BaseModel):
    classId: int
    className: str
    map50: Annotated[float, Field(description='Average Precision at IoU=0.50')]
    map50_95: Annotated[
        float, Field(description='Average Precision averaged over IoU=0.50:0.05:0.95')
    ]
    precision: float
    recall: float
    f1: float
    support: Annotated[
        int, Field(description='GT instance count for this class in the dataset')
    ]
    truePositives: int
    falsePositives: int
    falseNegatives: int


class ValidationRun(BaseModel):
    id: str
    modelId: str
    modelName: str
    datasetName: str
    split: DataSplit
    createdAt: Annotated[AwareDatetime, Field(description='ISO 8601 timestamp')]
    status: RunStatus
    imageCount: int
    classNames: Annotated[
        list[str], Field(description='Ordered list of class names; index == classId')
    ]
    aggregateMetrics: AggregateMetrics
    perClassMetrics: list[ClassMetrics]
    confusionMatrix: Annotated[
        list[list[int]],
        Field(description='confusionMatrix[trueClassId][predictedClassId] = count'),
    ]


class ImageFilters(BaseModel):
    class_: Annotated[str | None, Field(alias='class')] = None
    errorType: ErrorType | None = None
    dominantErrorType: Annotated[
        ErrorType | None,
        Field(
            description='Strict filter - only images whose dominant error matches. Used by patterns-page.\n'
        ),
    ] = None
    confMin: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    confMax: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    sort: SortOrder
    page: Annotated[int, Field(ge=1)]
    pageSize: Annotated[int, Field(ge=1)]


class GalleryParams(BaseModel):
    class_: Annotated[str | None, Field(alias='class')] = None
    errorType: ErrorType | None = None
    confMin: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    confMax: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    sort: SortOrder | None = None
    page: int | None = None
    pageSize: int | None = None


class PatternGroup(BaseModel):
    label: Annotated[
        str, Field(description='e.g. "bird", "false_positive", "low (0–0.4)"')
    ]
    count: Annotated[int, Field(description='Number of images in this group')]
    avgScore: Annotated[float, Field(description='Mean score across the group')]
    errorBreakdown: Annotated[
        dict[str, int],
        Field(description='Count of each ErrorType present in this group'),
    ]
    representativeImageIds: Annotated[
        list[str], Field(description='Top 3 worst images in the group', max_length=3)
    ]
    galleryParams: Annotated[
        GalleryParams | None,
        Field(description='Partial ImageFilters for deep-linking back to the gallery'),
    ] = None


class PatternsResponse(BaseModel):
    groupBy: PatternGroupBy
    groups: Annotated[
        list[PatternGroup], Field(description='Sorted by count descending')
    ]


class RunSummaryResponse(BaseModel):
    run: ValidationRun


class ImageListResponse(BaseModel):
    items: list[ImageListItem]
    total: int
    page: int
    pageSize: int


class ImageDetailResponse(BaseModel):
    image: ImageResult
